### ISSUE TITLE
Nur Links ab 6Mbit erlauben

### ISSUE THREAD

**Issue by FabianCernota** [FreifunkWesterwald/sites#1]
--disables 802.11b rates
		supported_rates = {6000, 9000, 12000, 18000, 24000, 36000, 48000, 54000},
		basic_rate = {6000, 9000, 18000, 36000, 54000},

Das muss in den Wifi24 Bliock. Dann kann es zwar passieren das uns sehr schwache Links verloren gehen aber die Nutzer werden dadurch bessere Performance erreichen und man sieht nicht die Freifunk SSID und am Ende bekommt man aufgrund der schlechten Verbindung noch nichtmal eine IP.

**Comment by paffy-27** [comment]
Ich würde es mal in die beta Firmware einbauen. Zum Testen.

**Comment by thepaffy** [comment]
#67ee499321fcd1c54937180f8ace1858955394d3
